name: pa004_311
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - seaborn
  - matplotlib
  - inflection
  - scipy=1.11.4
  - scikit-learn=1.2
  - numpy
  - jupyter
  - ipykernel
  - pip
  - pip:
      - scikit-plot
      - Boruta